# docker-compose.yml
version: '2.1'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    depends_on:
      - craft
    volumes_from:
      - craft
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./assets:/var/www/html/web/assets

  craft:
    image: urbantrout/craftcms:mysql
    depends_on:
      - mariadb
    volumes:
      - ./templates:/var/www/html/templates
      - ./assets:/var/www/html/web/assets
      - ..:/plugins/vz-address
    environment:
      DEPENDENCIES: >- # additional composer packages
        craftcms/redactor
        craftcms/feed-me
        [elivz/vzaddress:^2.0.0]/plugins/vz-address

      CRAFTCMS_EMAIL: eli@elivz.com
      CRAFTCMS_USERNAME: elivz
      CRAFTCMS_PASSWORD: test123
      CRAFTCMS_SITENAME: VZ Address Test Site
      CRAFTCMS_SITEURL: http://localhost # Optional

      DB_SERVER: mariadb
      DB_NAME: craft
      DB_USER: craft
      DB_PASSWORD: secret
      DB_DATABASE: craft
      DB_DRIVER: mysql
      DB_PORT: 3306

  mariadb:
    image: mariadb:10.1
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: craft
    volumes:
      # Persistent data
      - dbdata:/var/lib/mysql

volumes:
  dbdata: